[print_schema]
file = "src/database_components/diesel/schema.rs"
custom_type_derives = ["diesel::query_builder::QueryId", "Clone"]

[migrations_directory]
dir = "/home/skalse/Job/Rust/ExternalDeptBackend/migrations"
